version: '3.7'

services:

  worker:
    build:
      context: rq
      dockerfile: Dockerfile
      args:
        IMAGE: ${COMPOSE_PROJECT_NAME}
        TOOL_NAME: ${COMPOSE_PROJECT_NAME}
    image: ${COMPOSE_PROJECT_NAME}-worker
    volumes:
      - ./app/${COMPOSE_PROJECT_NAME}:/usr/src/app/${COMPOSE_PROJECT_NAME}:ro
    networks:
      - worker
      - redis
    command: rq worker ${COMPOSE_PROJECT_NAME} --url redis://redis:6379

  flask:
    build:
      context: flask
      dockerfile: Dockerfile
    environment:
      - FLASK_DEBUG=1
      - FLASK_RUN_PORT=8000
      - FLASK_APP=main.py
    image: flask
    container_name: flask
    volumes:
      - ./app:/usr/src/app:ro
    networks:
      - flask
      - redis
    command: gunicorn -w 4 -b 0.0.0.0:8000 main:app

networks:
  worker:
    name: worker
  flask:
    name: flask
  redis:
    external:
      name: redis
