version: '3.7'

services:

  worker:
    build:
      context: rq
      dockerfile: Dockerfile
      args:
        IMAGE: ${IMAGE}
    image: ${TOOL}-worker
#    container_name: ${TOOL}-worker
    volumes:
      - ./app/${TOOL}:/usr/src/app/${TOOL}:ro
      - ./app/${TOOL}.py:/usr/src/app/${TOOL}.py:ro
#      - ./src/app.py:/usr/src/app/app.py:ro
    networks:
      - worker
      - redis
    command: rq worker ${TOOL} --url redis://redis:6379

  flask:
    build:
      context: flask
      dockerfile: Dockerfile
    environment:
      - FLASK_DEBUG=1
      - FLASK_RUN_PORT=8000
      - FLASK_APP=main.py
    image: flask
    container_name: flask
    volumes:
      - ./app:/usr/src/app:ro
      # - ./src/app.py:/usr/src/app/app.py:ro
      # - ./src/main.py:/usr/src/app/main.py:ro
    networks:
      - flask
      - redis
    command: gunicorn -w 4 -b 0.0.0.0:8000 main:app

networks:
  worker:
    name: worker
  flask:
    name: flask
  redis:
    external:
      name: redis
