version: '3.7'

services:

  worker:
    build:
      context: rq
      dockerfile: Dockerfile
      args:
        IMAGE_NAME: ${BASE_IMAGE}
        TOOL_NAME: ${COMPOSE_PROJECT_NAME}
    image: rest/${COMPOSE_PROJECT_NAME}
    volumes:
      - ./tools/${COMPOSE_PROJECT_NAME}:/home/${COMPOSE_PROJECT_NAME}:ro
    networks:
      - worker
      - redis
    command: rq worker ${COMPOSE_PROJECT_NAME} --url redis://${REDIS}:6379

networks:
  worker:
    external:
      name: ${NETWORK}
  redis:
    external:
      name: redis
