version: '3.7'

services:

  worker:
    build:
      context: ..
      dockerfile: worker/Dockerfile
      args:
        BASE_IMAGE_NAME: ${BASE_IMAGE}
        PROJECT_NAME: ${COMPOSE_PROJECT_NAME}
        TOOL_DIR: ${TOOL_PATH}
    image: rest/${COMPOSE_PROJECT_NAME}-rest
    # volumes:
    #   - ./tools/${COMPOSE_PROJECT_NAME}:/home/tools/${COMPOSE_PROJECT_NAME}:ro
    networks:
      - worker
      - redis
    command: rq worker
                  --disable-job-desc-logging
                  ${COMPOSE_PROJECT_NAME}
                  --url redis://${REDIS}:6379

networks:
  worker:
    external:
      name: ${NETWORK}
  redis:
    external:
      name: redis
